"""DateTime datatype reverted

Revision ID: 2e75dfdca6ed
Revises: 0a7acf925377
Create Date: 2025-05-28 10:42:07.836089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e75dfdca6ed'
down_revision: Union[str, None] = '0a7acf925377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
