"""address added to patient table

Revision ID: dc1e6f488461
Revises: dbc2dba8fe0e
Create Date: 2025-05-28 09:47:53.056333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc1e6f488461'
down_revision: Union[str, None] = 'dbc2dba8fe0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('address', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'address')
    # ### end Alembic commands ###
