"""relationships corrected

Revision ID: e9f0c1a5e8b7
Revises: 2e75dfdca6ed
Create Date: 2025-05-29 12:21:55.843643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f0c1a5e8b7'
down_revision: Union[str, None] = '2e75dfdca6ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
